# fly.toml app configuration file generated for fightingtheboss-com on 2024-01-23T13:26:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fightingtheboss-com"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
